version: '3.8'
services:
  fuseki:
    ## Example:
    ## command: [ "--tdb2", "--update", "--loc", "databases/DB2", "/ds" ]
    build:
      context: fuseki
      dockerfile: Dockerfile
      args:
        - JENA_VERSION=4.4.0
    image: fuseki
    command: --mem /ds
    ports:
      - "3030:3030"
    volumes:
      - ./logs:/fuseki/logs
      - ./databases:/fuseki/databases
  jupyter:
    build:
      context: jupyter
      dockerfile: Dockerfile
    links:
      - "fuseki:sparqlapi"
    image: jupyter-sparql
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
